const {test} = require('@playwright/test')
const { SapiaInterviewPage } = require('../pageobjects/SapiaInterviewPage')


test('@Happy case with Sapia chat interview', async ({browser}) => {
    const context = await browser.newContext()
    await context.clearCookies()
    const page = await context.newPage()
    let sapiaInterviewPage = await new SapiaInterviewPage(page)
    await sapiaInterviewPage.goTo()
    await sapiaInterviewPage.inputFullName()
    await sapiaInterviewPage.inputEmail()
    await sapiaInterviewPage.inputPhone()
    await sapiaInterviewPage.inputLocation()
    await sapiaInterviewPage.clickAcceptBtn()
    await sapiaInterviewPage.inputImproveDayQuestion(50)
    await sapiaInterviewPage.inputMissDeadlineQuestion(50)
    await sapiaInterviewPage.inputLearnThingsQuestion(50)
    await sapiaInterviewPage.inputHelpTeamQuestion(50)
    await sapiaInterviewPage.inputDealDifficultQuestion(50)
    await sapiaInterviewPage.inputIdentifyQuestion()
    await sapiaInterviewPage.inputEnglishLanguageQuestion()
    await sapiaInterviewPage.inputAgeGroupQuestion()
    await sapiaInterviewPage.clickSubmitBtn()
    await sapiaInterviewPage.chooseRateQuestion()
    await sapiaInterviewPage.inputShareExperienceQuestion(15)
})

test('@Unhappy Verify Error dialog with 49 words in Sapia chat interview and click Continue', async ({browser}) => {
    const context = await browser.newContext()
    await context.clearCookies()
    const page = await context.newPage()
    let sapiaInterviewPage = await new SapiaInterviewPage(page)
    await sapiaInterviewPage.goTo()
    await sapiaInterviewPage.inputFullName()
    await sapiaInterviewPage.inputEmail()
    await sapiaInterviewPage.inputPhone()
    await sapiaInterviewPage.inputLocation()
    await sapiaInterviewPage.clickAcceptBtn()
    await sapiaInterviewPage.inputImproveDayQuestion(49)
    await sapiaInterviewPage.verifyErrorDialogAndContinue()
    await sapiaInterviewPage.inputMissDeadlineQuestion(49)
    await sapiaInterviewPage.verifyErrorDialogAndContinue()
    await sapiaInterviewPage.inputLearnThingsQuestion(49)
    await sapiaInterviewPage.verifyErrorDialogAndContinue()
    await sapiaInterviewPage.inputHelpTeamQuestion(49)
    await sapiaInterviewPage.verifyErrorDialogAndContinue()
    await sapiaInterviewPage.inputDealDifficultQuestion(49)
    await sapiaInterviewPage.verifyErrorDialogAndContinue()
    await sapiaInterviewPage.inputIdentifyQuestion()
    await sapiaInterviewPage.inputEnglishLanguageQuestion()
    await sapiaInterviewPage.inputAgeGroupQuestion()
    await sapiaInterviewPage.clickSubmitBtn()
    await sapiaInterviewPage.chooseRateQuestion()
    await sapiaInterviewPage.inputShareExperienceQuestion(15)
})

test('@Unhappy Verify Error dialog with 49 words in Sapia chat interview and click Edit to input 50 words again', async ({browser}) => {
    const context = await browser.newContext()
    await context.clearCookies()
    const page = await context.newPage()
    let sapiaInterviewPage = await new SapiaInterviewPage(page)
    await sapiaInterviewPage.goTo()
    await sapiaInterviewPage.inputFullName()
    await sapiaInterviewPage.inputEmail()
    await sapiaInterviewPage.inputPhone()
    await sapiaInterviewPage.inputLocation()
    await sapiaInterviewPage.clickAcceptBtn()
    await sapiaInterviewPage.inputImproveDayQuestion(49)
    await sapiaInterviewPage.verifyErrorDialogAndEdit()
    await sapiaInterviewPage.inputImproveDayQuestion(2)
    await sapiaInterviewPage.inputMissDeadlineQuestion(49)
    await sapiaInterviewPage.verifyErrorDialogAndEdit()
    await sapiaInterviewPage.inputMissDeadlineQuestion(2)
    await sapiaInterviewPage.inputLearnThingsQuestion(49)
    await sapiaInterviewPage.verifyErrorDialogAndEdit()
    await sapiaInterviewPage.inputLearnThingsQuestion(2)
    await sapiaInterviewPage.inputHelpTeamQuestion(49)
    await sapiaInterviewPage.verifyErrorDialogAndEdit()
    await sapiaInterviewPage.inputHelpTeamQuestion(2)
    await sapiaInterviewPage.inputDealDifficultQuestion(49)
    await sapiaInterviewPage.verifyErrorDialogAndEdit()
    await sapiaInterviewPage.inputDealDifficultQuestion(2)
    await sapiaInterviewPage.inputIdentifyQuestion()
    await sapiaInterviewPage.inputEnglishLanguageQuestion()
    await sapiaInterviewPage.inputAgeGroupQuestion()
    await sapiaInterviewPage.clickSubmitBtn()
    await sapiaInterviewPage.chooseRateQuestion()
    await sapiaInterviewPage.inputShareExperienceQuestion(15)
})


